### PR TITLE
Support for additional OAuth2 providers

### LINKED ISSUE #599: Allow other OAuth2 Providers and not just Google
It would be very useful to allow other logins via other OAuth2 providers e.g., Microsoft Azure. 

There are currently hard coded URIs and logic that involves Google People API.

### PR DESCRIPTION
**Pull request by james-perretta**
Fixes #599

### CODE REVIEW

**Comment by liamoreilly** [comment]
Hi @james-perretta,

Is there anything I need to do here? I guess I should not review my own code :-)

Liam

**Comment by james-perretta** [comment]
@liamoreilly can you send me an example of what your (dev_)oauth2_secrets.json file looks like for Azure?

**Comment by liamoreilly** [comment]
Hi @james-perretta,

My current secrets file is:
```
{"web":{
    "client_id":"1",
    "auth_uri":"https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
    "token_uri":"https://login.microsoftonline.com/common/oauth2/v2.0/token",
    "client_secret":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "redirect_uris":["https://autograder.my.domain/api/oauth2callback/"],
    "javascript_origins":["https://autograder.my.domain"]
}}
```

I started with the secrets file downloaded from Google and then changed the relevant pieces above to match my OAuth2 client settings for Microsoft developer.

I found I could remove `project_id` and `auth_provider_x509_cert_url` that was part of the Google secrets file without any ill effects.

The `auth_uri` and `token_uri` are likely to remain exactly as above for most people using this. They may be altered if the OAuth2 client is set up for different tenants - but the user could configure as needed in such a case.

**Comment by james-perretta** [comment]
@liamoreilly Thanks! I should be able to merge this later this afternoon.

**Comment by james-perretta** [comment]
Hmmm so the request to `https://graph.microsoft.com/v1.0/me` is coming back with an "insufficient privileges" error:
```
{
    'error': {
        'code': 'Authorization_RequestDenied', 
        'message': 'Insufficient privileges to complete the operation.', 
        'innerError': {
            'date': '2020-10-26T18:20:52', 
            'request-id': 'afd837a8-6a74-40e3-bded-2e20df7f4dc1', 
            'client-request-id': 'afd837a8-6a74-40e3-bded-2e20df7f4dc1'
        }
    }
}
```

Any ideas? Is there some configuration option I missed?

**Comment by liamoreilly** [comment]
Hi,

This URL is only able to be accessed once the OAuth2 token has been obtained. 

I set up my own OAuth2 client as follows. This allows any personal Microsoft account to sign in to my "app".

I went to https://portal.azure.com/#home and signed in with a personal account.
Then to Azure Active Directory
Then to App registrations (direct URL? https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps)

I created an App using the option "Accounts in this organizational directory only (Default Directory only - Single tenant)" and configured the redirect URIs.

You then need to configure Certificates & secrets.
I created a new client secrete that never expired - this is the OAuth2 client secret used in the json file.

Does that help at all?
Liam

**Comment by james-perretta** [comment]
Hmm interesting, I actually had to configure it as a multi-tenant app in order for it to let me use the `/common` auth_uri and token_uri endpoints you shared for the secrets file. 

Currently, I can get through the steps of signing into my microsoft account, but when it calls the oauth2callback is when I get this error. I can try it with a personal microsoft account instead of my Umich one and see if it makes any difference.
 
**UPDATE**: It doesn't let me sign in with a personal account--the login page says, "You can't sign in here with a personal account. Use your work or school account instead" when I try.

**Comment by liamoreilly** [comment]
If you like I could email you my secret and other details so you can test with my app. I would just need to add your own redirect for the URL. 

I am not able to test the business side of things as I do not have access to any. Once I ask my uni to create me an OAuth2 client then I would know if it works with the business side of things. But I can't do that until it is deployed.

**Comment by liamoreilly** [comment]
As another idea. If you look at the end-points (button on the Azure site that lists all the endpoints you should use). You might not be supposed to be using "common" for your multi-tenant end-point (auth URL and token URL).

**Comment by james-perretta** [comment]
That would be great if you could email me the secrets: help@autograder.io (I'm the only one on that address at the moment).

I'll also take a look at the endpoints and see what I can come up with. Thanks!

**Comment by james-perretta** [comment]
@liamoreilly What permissions do you have granted to the application in the azure dashboard? Here's what mine looks like:

Screenshot from 2020-10-26 17-19-17

**Comment by liamoreilly** [comment]
That page is identical for me. Just User.Read.

**Comment by james-perretta** [comment]
Ok, it works with the secrets you sent me, but only if I use a personal account instead of my umich one. I'd like to do a little more investigating to see if I can get it working with my umich account.

**Comment by james-perretta** [comment]
@liamoreilly Thanks for your help with this!

**Comment by liamoreilly** [comment]
@james-perretta Thanks for helping me along the way. It was the first time I have contributed to an open-source project actually :-)

**Comment by liamoreilly** [comment]
@james-perretta Sorry to ask, but do you have an idea about when will this get merged into a "release"? These changes seem to be on the develop branch right now. The branch release-4.1.x is one commit behind the merge that includes these changes.
Thanks.

**Comment by james-perretta** [comment]
@liamoreilly Sorry for not being more transparent about this--I generally prefer to release major changes (or changes to mission-critical parts of the software such as authentication) between terms rather than in the middle of a term. That said, the current term is just about over! There are a few website things I still need to wrap up, but I should be releasing autograder-server 4.2.x  and ag-website-vue 1.4.x by the end of the week.

**Comment by liamoreilly** [comment]
@james-perretta Thanks. That makes a lot of sense. No rush either. We have now used autograder on one of our courses and it worked very well. We are doing a "proper" deployment for next term - so waiting a few weeks for the new release is not a problem.

**Pull request merged**
